@{
from rosidl_typesupport_zzdds_cpp import all_messages
from rosidl_typesupport_zzdds_cpp import c_header_guard
from rosidl_pycommon import convert_camel_case_to_lower_case_underscore
messages = all_messages(content)
guard = c_header_guard(package_name, interface_path)
stem = convert_camel_case_to_lower_case_underscore(interface_path.stem)
}@
// generated by rosidl_typesupport_zzdds_c; do not edit
#ifndef @(guard)
#define @(guard)

#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_typesupport_interface/macros.h"
#include "@(package_name)/@(interface_path.parents[0])/detail/@(stem)__struct.h"

#ifdef __cplusplus
#include "zidl_cdr.h"
@[for message in messages]@
@{
type_ = message.structure.namespaced_type
namespaces = list(type_.namespaces)
ctype = '__'.join(type_.namespaced_name())
}@
@[for namespace in namespaces]@
namespace @(namespace) {
@[end for]@
namespace typesupport_zzdds_c {
bool cdr_serialize(const @(ctype) & ros_message, ZidlCdrWriter * writer);
bool cdr_deserialize(ZidlCdrReader * reader, @(ctype) & ros_message);
}  // namespace typesupport_zzdds_c
@[for namespace in reversed(namespaces)]@
}  // namespace @(namespace)
@[end for]@
@[end for]@
#endif

#ifdef __cplusplus
extern "C"
{
#endif
@[for message in messages]@
@{
type_ = message.structure.namespaced_type
}@
const rosidl_message_type_support_t *
ROSIDL_TYPESUPPORT_INTERFACE__MESSAGE_SYMBOL_NAME(
  rosidl_typesupport_zzdds_c,
  @(', '.join(type_.namespaced_name())))();
@[end for]@
#ifdef __cplusplus
}
#endif

#endif  // @(guard)
