@{
from rosidl_typesupport_zzdds_cpp import all_messages
from rosidl_typesupport_zzdds_cpp import c_deserialize_members
from rosidl_typesupport_zzdds_cpp import c_serialize_members
from rosidl_typesupport_zzdds_cpp import c_symbol
from rosidl_typesupport_zzdds_cpp import dds_type_name
from rosidl_typesupport_zzdds_cpp import filter_field_cases
from rosidl_typesupport_zzdds_cpp import has_key
from rosidl_typesupport_zzdds_cpp import nested_headers
from rosidl_parser.definition import Service
from rosidl_pycommon import convert_camel_case_to_lower_case_underscore
messages = all_messages(content)
services = list(content.get_elements_of_type(Service))
stem = convert_camel_case_to_lower_case_underscore(interface_path.stem)
base = '/'.join([package_name] + list(interface_path.parents[0].parts) + ['detail', stem])
}@
// generated by rosidl_typesupport_zzdds_c; do not edit
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <cstdlib>

#include "@(base)__functions.h"
#include "@(base)__rosidl_typesupport_zzdds_c.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"
#include "rosidl_runtime_c/string_functions.h"
#include "rosidl_runtime_c/u16string_functions.h"
#include "rosidl_typesupport_zzdds_c/identifier.hpp"
#include "rosidl_typesupport_zzdds_c/message_type_support.hpp"
#include "rosidl_typesupport_zzdds_cpp/message_type_support.hpp"

@[for header in nested_headers(messages)]@
#include "@(header.replace('__rosidl_typesupport_zzdds_cpp.hpp', '__functions.h'))"
#include "@(header.replace('__rosidl_typesupport_zzdds_cpp.hpp', '__rosidl_typesupport_zzdds_c.h'))"
@[end for]@

@[for message in messages]@
@{
type_ = message.structure.namespaced_type
ctype = '__'.join(type_.namespaced_name())
namespaces = list(type_.namespaces)
symbol = c_symbol(type_)
keyed = has_key(message)
message_stem = convert_camel_case_to_lower_case_underscore(type_.name)
}@
@[for namespace in namespaces]@
namespace @(namespace)
{
@[end for]@
namespace typesupport_zzdds_c
{

static void * create_ros_message_@(message_stem)()
{
  auto * message = static_cast<@(ctype) *>(std::malloc(sizeof(@(ctype))));
  if (message != nullptr && !@(ctype)__init(message)) {
    std::free(message);
    message = nullptr;
  }
  return message;
}

static void destroy_ros_message_@(message_stem)(void * untyped)
{
  if (untyped != nullptr) {
    @(ctype)__fini(static_cast<@(ctype) *>(untyped));
    std::free(untyped);
  }
}

bool cdr_serialize(const @(ctype) & ros_message, ZidlCdrWriter * writer)
{
@(c_serialize_members(message))
  return true;
}

bool cdr_deserialize(ZidlCdrReader * reader, @(ctype) & ros_message)
{
@(c_deserialize_members(message))
  return true;
}

static bool serialize_@(message_stem)(const void * untyped, ZidlCdrWriter * writer)
{
  if (untyped == nullptr || writer == nullptr || writer->xcdr_version != ZIDL_XCDR1) {
    return false;
  }
  if (zidl_cdr_write_encap(writer) != ZIDL_CDR_OK) {
    return false;
  }
  return cdr_serialize(*static_cast<const @(ctype) *>(untyped), writer);
}

static bool deserialize_@(message_stem)(ZidlCdrReader * reader, void * untyped)
{
  return reader != nullptr && untyped != nullptr && reader->xcdr_version == ZIDL_XCDR1 &&
         cdr_deserialize(reader, *static_cast<@(ctype) *>(untyped));
}

static size_t get_serialized_size_@(message_stem)(const void * untyped)
{
  ZidlCdrWriter writer{};
  if (zidl_cdr_writer_init(&writer, ZIDL_XCDR1) != ZIDL_CDR_OK) {
    return SIZE_MAX;
  }
  const bool ok = serialize_@(message_stem)(untyped, &writer);
  const size_t result = ok ? writer.len : SIZE_MAX;
  zidl_cdr_writer_deinit(&writer);
  return result;
}

static bool get_field_from_cdr_@(message_stem)(
  const uint8_t * payload, size_t payload_len, const char * field, size_t field_len,
  zzdds_filter_value * out, uint8_t * scratch, size_t scratch_len)
{
  (void)field_len;
  (void)scratch_len;
  if (payload == nullptr || field == nullptr || out == nullptr || scratch == nullptr) {
    return false;
  }
  ZidlCdrReader reader{};
  @(ctype) ros_message{};
  if (!@(ctype)__init(&ros_message)) {
    return false;
  }
  if (zidl_cdr_reader_init(&reader, payload, payload_len) != ZIDL_CDR_OK ||
    !cdr_deserialize(&reader, ros_message))
  {
    @(ctype)__fini(&ros_message);
    return false;
  }
  const bool found = [&]() {
@(filter_field_cases(message, c_layout=True, indent=4))
  }();
  @(ctype)__fini(&ros_message);
  return found;
}

@[if keyed]@
static bool compute_key_hash_@(message_stem)(const void * untyped, uint8_t hash[16])
{
  if (untyped == nullptr || hash == nullptr) {
    return false;
  }
  ZidlCdrWriter key_writer{};
  ZidlCdrWriter * writer = &key_writer;
  if (zidl_cdr_writer_init(writer, ZIDL_XCDR1) != ZIDL_CDR_OK) {
    return false;
  }
  zidl_cdr_writer_set_byte_order(writer, ZIDL_CDR_BE);
  const auto & ros_message = *static_cast<const @(ctype) *>(untyped);
@(c_serialize_members(message, indent=2, keys_only=True))
  zidl_cdr_compute_key_hash(writer->buf, writer->len, hash);
  zidl_cdr_writer_deinit(writer);
  return true;
}
@[end if]@

static const rosidl_typesupport_zzdds_cpp::message_type_support_callbacks_t
callbacks_@(message_stem) = {
  "@('::'.join(namespaces))", "@(type_.name)", "@(dds_type_name(type_))",
  serialize_@(message_stem), deserialize_@(message_stem),
  create_ros_message_@(message_stem), destroy_ros_message_@(message_stem),
  get_serialized_size_@(message_stem), @('true' if keyed else 'false'),
  @('compute_key_hash_' + message_stem if keyed else 'nullptr'),
  get_field_from_cdr_@(message_stem),
};

static const rosidl_message_type_support_t handle_@(message_stem) = {
  rosidl_typesupport_zzdds_c::typesupport_identifier,
  &callbacks_@(message_stem),
  rosidl_typesupport_zzdds_c::get_message_typesupport_handle_function,
  &@(symbol)__get_type_hash,
  &@(symbol)__get_type_description,
  &@(symbol)__get_type_description_sources,
};

}  // namespace typesupport_zzdds_c
@[for namespace in reversed(namespaces)]@
}  // namespace @(namespace)
@[end for]@

extern "C"
const rosidl_message_type_support_t *
ROSIDL_TYPESUPPORT_INTERFACE__MESSAGE_SYMBOL_NAME(
  rosidl_typesupport_zzdds_c,
  @(', '.join(type_.namespaced_name())))()
{
  return &@('::'.join(namespaces))::typesupport_zzdds_c::handle_@(message_stem);
}
@[end for]@

@[for service in services]@
@{
service_type = service.namespaced_type
service_namespaces = list(service_type.namespaces)
service_symbol = c_symbol(service_type)
request_stem = convert_camel_case_to_lower_case_underscore(service.request_message.structure.namespaced_type.name)
response_stem = convert_camel_case_to_lower_case_underscore(service.response_message.structure.namespaced_type.name)
event_stem = convert_camel_case_to_lower_case_underscore(service.event_message.structure.namespaced_type.name)
}@
@[for namespace in service_namespaces]@
namespace @(namespace) {
@[end for]@
namespace typesupport_zzdds_c {
static const rosidl_service_type_support_t handle_@(stem) = {
  rosidl_typesupport_zzdds_c::typesupport_identifier, nullptr,
  rosidl_typesupport_zzdds_c::get_service_typesupport_handle_function,
  &handle_@(request_stem), &handle_@(response_stem), &handle_@(event_stem),
  nullptr, nullptr,
  &@(service_symbol)__get_type_hash,
  &@(service_symbol)__get_type_description,
  &@(service_symbol)__get_type_description_sources,
};
}
@[for namespace in reversed(service_namespaces)]@
}
@[end for]@
extern "C" const rosidl_service_type_support_t *
ROSIDL_TYPESUPPORT_INTERFACE__SERVICE_SYMBOL_NAME(
  rosidl_typesupport_zzdds_c, @(', '.join(service_type.namespaced_name())))()
{
  return &@('::'.join(service_namespaces))::typesupport_zzdds_c::handle_@(stem);
}
@[end for]@
