@{
from rosidl_typesupport_zzdds_cpp import all_messages
from rosidl_typesupport_zzdds_cpp import header_guard
from rosidl_pycommon import convert_camel_case_to_lower_case_underscore
messages = all_messages(content)
guard = header_guard(package_name, interface_path)
stem = convert_camel_case_to_lower_case_underscore(interface_path.stem)
}@
// generated by rosidl_typesupport_zzdds_cpp; do not edit
#ifndef @(guard)
#define @(guard)

#include "zidl_cdr.h"
#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_typesupport_zzdds_cpp/message_type_support.hpp"

@[for message in messages]@
#include "@('/'.join(list(message.structure.namespaced_type.namespaces) + ['detail', stem + '__struct.hpp']))"
@[end for]@

@[for message in messages]@
@{
type_ = message.structure.namespaced_type
namespaces = list(type_.namespaces)
}@
@[for namespace in namespaces]@
namespace @(namespace)
{
@[end for]@
namespace typesupport_zzdds_cpp
{
bool cdr_serialize(const @('::'.join(type_.namespaced_name())) & ros_message, ZidlCdrWriter * writer);
bool cdr_deserialize(ZidlCdrReader * reader, @('::'.join(type_.namespaced_name())) & ros_message);
}  // namespace typesupport_zzdds_cpp
@[for namespace in reversed(namespaces)]@
}  // namespace @(namespace)
@[end for]@

namespace rosidl_typesupport_zzdds_cpp
{
template<>
ROSIDL_TYPESUPPORT_ZZDDS_CPP_EXPORT
const rosidl_message_type_support_t *
get_message_type_support_handle<@('::'.join(type_.namespaced_name()))>();
}  // namespace rosidl_typesupport_zzdds_cpp
@[end for]@

#endif  // @(guard)
